# -- coding: utf-8 --
# 复制本文件为 config.py 后填写个人信息（勿直接编辑本文件）
# Copy this file to config.py and fill in your info (do NOT edit this file directly)

# ============ 个人信息 / Personal Info ============
YOU_NAME = "张三"  # 姓名，示例："张三" / Your name
YOU_ID = "0000000000"  # 学号，示例："2024000000" / Student ID

# ============ Cookie ============
# Cookie 统一存放在项目根目录 cookie.txt，程序启动时自动读取，无需在此配置。
# 获取：浏览器登录统一身份认证并进入场馆预约系统 → F12 → Network → 任选请求（如 getTimeList.do）复制 Cookie 整段。
# 写入：手动把整段 Cookie 粘贴到项目根目录的 cookie.txt（覆盖原内容）。
# 注意：Cookie 当天有效，0 点后自动失效。建议在开抢当天（预约日前一天）0 点后获取 Cookie 并启动脚本。

# ============ 预约参数 / Booking Params ============
YYLX = "1.0"  # 预约类型：羽毛球/排球/网球/壁球/乒乓球="1.0"，健身房/足球/篮球="2.0"
typeOfSport = "001"  # 运动类型：001羽毛球 002足球 003排球 004网球 005篮球 006壁球 007一楼重量型健身 008二楼有氧型健身 013乒乓球
appointment_day = "2026-01-01"  # 预约日期，格式 YYYY-MM-DD，示例："2026-01-01"
appointment_time_start = "20:00"  # 预约开始时间，格式 HH:MM，示例："20:00"
cnt = 1  # 预约场次数目（1 或 2），一个时间段只能约一场，单人最多约两场

# ============ 羽毛球场地 / Badminton Court ============
campus = "1"  # 校区："1"=粤海，"2"=丽湖
target_room = ""  # 指定场地，留空则随机；粤海示例："A3"，丽湖示例："至畅羽毛球1号场"